### ISSUE TITLE
Update and expand on staging principles esp guide to lofted trajectories.

### ISSUE THREAD

**Issue by zorg2044** [friznit/Unofficial-BDB-Wiki#37]
Will do this when I have a moment with mechjeb PVG settings and some output form the MJ flight recorder too.

Saturn IB and Atlas CELV in particular could be challenging craft for players in 2.5/2.7 scale

**Comment by zorg2044** [comment]
Er I need to get back to this, what I've written so far is a bit incomplete.

**Comment by friznit** [comment]
I've just been reading it!  It's somewhere between a KSP launch tutorial and a guide to getting low TWR BDB rockets into orbit.  Admittedly it started life as the former (mostly because I had no idea what GTO is, why it's useful, or what kick stages were).  I think it would be good to structure it in two parts:  a basic tutorial explaining some of the fundamentals of getting stuff into orbit, and the second part covering lofted orbits, PVG and any other tricks.

**Comment by zorg2044** [comment]
Yeah good point
